version: '3.8'

services:
  llama-server:
    image: ghcr.io/ggerganov/llama.cpp:server-cuda-b4068
    ports:
      - "8880:8080"
    volumes:
      - ./models/:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      -m /models/Llama-3.2-3B-Instruct-Q6_K.gguf
      -c 2048
      --host 0.0.0.0
      --port 8080
      --n-gpu-layers 64
    networks:
      - llama-network
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility

networks:
  llama-network:
    driver: bridge